- atom.ejs
- rss2.ejs
Currently, root path is not considered in feed plugin.
if root is described in `_config.yml` like this
```
url: http://domain.url
root: /blog/
```
then each url of posts will be
- domain.url/blog/permalink1
- domain.url/blog/permalink2
but urls in feed are not matched.
> apply root path to permalinks

- README.md
- atom.xml
- index.js
- rss2.xml
> **[PubSubHubbub](https://github.com/pubsubhubbub/PubSubHubbub)** is an open protocol for distributed publish/subscribe communication on the Internet. It generalizes the concept of webhooks and allows data producers and data consumers to work in a decoupled way.
> PubSubHubbub provides a way to subscribe, unsubscribe and receive updates from a resource, whether it's an RSS or Atom feed or any web accessible document (JSON...).
This patch add the PubSubHubbub Discovery protocol support to atom.xml and rss2.xml. Feedly and Inoreader support PubSubHubbub Subscription protocol now, so it will help your subscribers get notification faster.
> Support PubSubHubbub protocol

- atom.xml
- lib/generator.js
support ["atom:icon"](https://tools.ietf.org/html/rfc4287#page-19) element with `config.email` using [hexojs gravatar helper](https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/gravatar.js)
> Support for "atom:icon" element

- README.md
- atom.xml
- rss2.xml
[Flexy](https://github.com/sjaakvandenberg/flexy), the theme I'm currently using with Hexo, uses the `intro` front-matter tag to generate a short description for the post.
Supporting it directly in the RSS feed generator could save a lot of duplicate lines in posts' headers at seemingly no expense.
> Support "intro" tag as description

- README.md
- lib/generator.js
This PR improves PR #57 and adds possibility to customize atom:icon by specifying `icon` property in feed section of `_config.yml`.
> Add ability to customize atom:icon

- atom.xml
- rss2.xml
- test/index.js
When a `post` has an `image` front matter, it gets displayed as:
- `<enclosure type=image url="http://bloguri/{{ post.image }}" />` for RSS2 output
- `<content type=image src="http://bloguri/{{ post.image }}" />` for Atom output
> Add image enclosure with post.image metadata

- .gitignore
- .npmignore
- LICENSE
- index.js
- package.json
- test/index.js
- remove object-assign
- remove useless files from npm module
- `npm pack --dry-run`
```
npm notice
npm notice package: hexo-generator-feed@1.2.2
npm notice === Tarball Contents ===
npm notice 1.1kB package.json
npm notice 2.3kB atom.xml
npm notice 674B  index.js
npm notice 1.1kB LICENSE
npm notice 1.9kB README.md
npm notice 2.0kB rss2.xml
npm notice 1.4kB lib/generator.js
npm notice === Tarball Details ===
npm notice name:          hexo-generator-feed
npm notice version:       1.2.2
npm notice filename:      hexo-generator-feed-1.2.2.tgz
npm notice package size:  4.1 kB
npm notice unpacked size: 10.5 kB
npm notice shasum:        6bd84f1bf62e1bc0b43c60aa80fc3930767e7cb9
npm notice integrity:     sha512-xfNbBo3BZE+G3[...]81vhMiiHgRmiA==
npm notice total files:   7
npm notice …
```
> some chore update

- index.js
Sorry, I made mistake when reviewed #70 
Current master branch has an error. `Object.assign` spell is wrong.
```sh
ERROR Plugin load failed: hexo-generator-feed
TypeError: Object.assignn is not a function
```
> fix: TypeError: Object.assignn is not a function

- .jscsrc
- .npmignore
- .travis.yml
- lib/generator.js
- package.json
- test/index.js
[jscs has already merged with eslint](https://www.npmjs.com/package/jscs). 
I fix 6 eslint error after migrate to eslint.
```sh
$ yarn eslint
$ eslint .
./hexo-generator-feed/lib/generator.js
7:24  error  "hexo" is not published                                            node/no-unpublished-require
14:22  error  Unexpected control character(s) in regular expression: \x00, \x1f  no-control-regex
./hexo-generator-feed/test/index.js
16:22  error  Unexpected control character(s) in regular expression: \x00, \x1f            no-control-regex
36:3   error  Unnecessary parentheses around expression                                    no-extra-parens
39:3   error  Combine this with the previous 'var' statement with uninitialized variables  one-var
116:35  error  Unnecessary escape character: \: …
```
> chore(package): delete jscs & use eslint

- atom.xml
- lib/generator.js
- package.json
- rss2.xml
- test/index.js
By not escaping domains with encodeURI (only path)
See #63
> Support IDN

- lib/generator.js
- package.json
[`gravatar()`](https://github.com/hexojs/hexo-util/pull/81) is available on hexo-util [1.2.0](https://github.com/hexojs/hexo-util/releases/tag/1.2.0).
> refactor: use gravatar from hexo-util

- README.md
- index.js
- lib/autodiscovery.js
- package.json
- test/index.js
Many (most?) themes already offer this feature, but this plugin should've added it in the first place.
ref: http://www.rssboard.org/rss-autodiscovery
credit: [meta_generator.js](https://github.com/hexojs/hexo/blob/master/lib/plugins/filter/meta_generator.js)
> feat: add rss autodiscovery

- atom.xml
- lib/generator.js
- rss2.xml
- test/index.js
The current approach does not encode the root value, this PR fixes that.
Similar to https://github.com/hexojs/hexo-generator-sitemap/pull/66
This PR is necessary to be compatible with hexo v4 and v3 or older (forward & backward compatibility).
Supersede #88
> fix(IDN): uriencode root value

- atom.xml
- lib/generator.js
- rss2.xml
- test/index.js
I configured `feed.icon` in the `config.yml` file.
but that icon was not exposed when creating the feed xml file.
So, I add in `rss2.xml` :
``` 
<url> {{(url + config.feed.icon) | uriencode}} </ url>
```
and I see that it works.
> Add : feed icon to rss2.xml

- README.md
- index.js
- lib/autodiscovery.js
- lib/generator.js
- test/index.js
Fix #59 
How to test:
``` diff
package.json
-  "hexo-generator-feed": "^2.0.0"
+  "hexo-generator-feed": "curbengh/hexo-generator-feed#atom-rss2"
```
``` sh
$ rm -rf node_modules/ && npm i
```
``` yml
_config.yml
feed:
type:
- 'atom'
- 'rss2'
```
``` sh
$ hexo clean && hexo g
```
cc @mythsman
> feat: support output in both atom and rss2

- atom.xml
As per https://tools.ietf.org/html/rfc4287#section-1.2, the correct xml namespace is "http://www.w3.org/2005/Atom". When https is used, some feed validators will fail validation, even though the "https" version of that URL is also valid.  
fixes #104
> Updated Atom.xml to use correct namespace

- lib/autodiscovery.js
- lib/generator.js
- test/index.js
see https://github.com/tomap/hexo-theme-minidyne-demo/pull/5/commits/2ddea217338f62bdfba9f1d8f83d106d6f9e6d0c
The fix is a bit dumb, but I don't feel we need to generate an empty atom or rss file in that case.
Related to issue #43 (last comments)
> handle sites with no posts

- index.js
Handle following edge cases:
``` yml
type:
- atom
- rss2
path: 'feed/atom.xml'
```
---
The following config previously would error out when executing
https://github.com/hexojs/hexo-generator-feed/blob/dd558c65d1a6dd0a4cc9e6434e13dd552821d320/index.js#L58
``` yml
type:
- atom
- rss2
path: 
- 'feed/atom.xml'
```
---
``` yml
type:
- atom
- rss2
path: []
```
---
Noticed while testing https://github.com/hexojs/hexo-generator-feed/pull/110
> fix: handle zero length 'config.path'

- index.js
currently L62 only handles `undefined`, not `null` (which is an `object` type). This PR allows it to handle `object`, `number` and `string` types.
`type:` and `path:` also default to an array since a string will always be converted to array.
> fix(autodiscovery): check boolean type instead of undefined

- index.js
- lib/autodiscovery.js
- test/index.js
Fixes #112 
Existing theme expects `feed.path` to be a string, but previous PR https://github.com/hexojs/hexo-generator-feed/pull/96 converts it to array. This PR prevents the conversion.
cc @mikolaje @yrpang @AlynxZhou @stevenjoezhang
> fix: compatibility with existing theme

- README.md
- index.js
- lib/generator.js
- test/custom.xml
- test/index.js
As suggested in https://github.com/hexojs/hexo-generator-feed/issues/101#issuecomment-544144090, cc @freak3dot
How to test:
``` diff
package.json
-  "hexo-generator-feed": "^2.0.0"
+  "hexo-generator-feed": "curbengh/hexo-generator-feed#custom-template"
```
``` sh
$ rm -rf node_modules/ && npm i
```
``` yml
_config.yml
exclude:
- 'custom.xml'
feed:
type: 'atom'
template: './source/custom.xml'
```
``` sh
$ hexo clean && hexo g
```
---
Following configs are supported:
``` yml
feed:
type:
- 'atom'
- 'rss2'
template:
- './source/_atom.xml'
- './source/_rss2.xml'
```
``` yml
feed:
type:
- 'atom'
- 'rss2'
template:
- './source/_atom.xml'
```
> feat: custom template

- index.js
eslint-config-hexo is going to enforce [no-multi-assign](https://github.com/hexojs/eslint-config-hexo/pull/22/files#diff-139d26542d80f293e0b4ff01913d24ccR88).
> style: no-multi-assign

- package.json
- test/index.js
- test/parse.js
I find cheerio's syntax a bit clunky to parse the xml. In contrast, camaro parses it into json, which makes it easier to grab a specific element. The package size is [minimal](https://bundlephobia.com/result?p=camaro@4.1.2) (especially compared to [cheerio's](https://bundlephobia.com/result?p=cheerio@1.0.0-rc.3)).
cheerio is still used to parse html, to test autodiscovery.
I started to use camaro in https://github.com/hexojs/hexo-migrator-rss/pull/34.
> test: use camaro to parse xml

- atom.xml
- rss2.xml
Current behavior:
``` xml
<summary type="html">
this is an excerpt
</summary>
```
Expected behavior:
``` xml
<summary type="html">this is an excerpt</summary>
```
> fix(template): remove extra spacing

- test/parse.js
Valid value in RSS2 is,
``` xml
<atom:link href="http://example.com" rel="self" type="application/rss+xml"/>
```
`rss/channel/atom:link` XPath incorrectly assumes
``` xml
<atom:link>http://example.com</atom:link>
```
> fix(parseFeed): parse href attribute not text

- lib/generator.js
- test/index.js
This PR is an update to #29.
This supposed to be a small PR, but I've encountered some issues regarding the base URL.
The [`full_url_for`](https://github.com/hexojs/hexo-util/blob/master/lib/full_url_for.js#L27) function expects the `config.url` not to end with a forward slash. Otherwise it will create a double slash URL, e.g. `http://example.com//atom.xml` (notice that a double slash replacement happens only _after_ the base URL).
I was wondering how the icon feature (#102) can be using `full_url_for` with the current code and not run into any double slash issues. The answer is: it doesn't handle this case. The [unit tests](https://github.com/hexojs/hexo-generator-feed/pull/102/files#diff-910eb6f57886ca16c136101fb1699231R240) are simply running against a custom base URL without an ending …
> Render an absolute feed URL

- atom.xml
- lib/generator.js
- test/index.js
`url + post.image` is problematic because `post.image` may have a slash prefix and cause the result to have double slash.
> refactor: utilize full_url_for()

- atom.xml
- package.json
- rss2.xml
- test/index.js
- test/parse.js
compatibility with https://github.com/hexojs/hexo/pull/3887 https://github.com/hexojs/hexo/pull/4278
> fix: compatibility with null post.updated
